// ********RoostGPT********
// Test generated by RoostGPT for test checkJestConfigChanges using AI Type Open AI and AI Model gpt-4

// ********RoostGPT********
const expect = require("chai").expect;
const { averageTemp } = require("../prepared-for-the-weather");

describe("averageTemp()", function () {
  it("should return the average of two numbers", function () {
    const result = averageTemp(2, 4);
    expect(result).to.equal(3);
  });

  it("should return NaN when a non-number is provided", function () {
    const result = averageTemp("2", 4);
    expect(result).to.be.NaN;
  });

  it("should return NaN when no arguments are provided", function () {
    const result = averageTemp();
    expect(result).to.be.NaN;
  });
});
