// ********RoostGPT********
// Test generated by RoostGPT for test checkJestConfigChanges using AI Type Open AI and AI Model gpt-4

// ********RoostGPT********
const chai = require("chai");
const expect = chai.expect;
const sinon = require("sinon");
const sinonChai = require("sinon-chai");
chai.use(sinonChai);
const app = require("../app");

describe("printLine", function () {
  let consoleLog;

  beforeEach(function () {
    consoleLog = sinon.spy(console, "log");
  });

  afterEach(function () {
    console.log.restore();
  });

  it("should print text with checkmark and green color if required is true", function () {
    app.printLine(true, "Test text");
    expect(consoleLog).to.have.been.calledWith("\u2714 Test text");
  });

  it("should print text with crossmark and red color if required is false", function () {
    app.printLine(false, "Test text");
    expect(consoleLog).to.have.been.calledWith("\u2716 Test text");
  });
});
