// ********RoostGPT********
// Test generated by RoostGPT for test checkJestConfigChanges using AI Type Open AI and AI Model gpt-4

// ********RoostGPT********
const expect = require("chai").expect;
const { processResults } = require("../fetch-weather");

describe("Fetch Weather", function () {
  describe("#processResults()", function () {
    it("should return correct values when allResults is valid", function () {
      const allResults = {
        main: {
          temp_min: 288.15, // 15C
          temp_max: 293.15, // 20C
        },
        rain: {
          "3h": 2,
        },
        clouds: {
          all: 50,
        },
      };
      const result = processResults(allResults);
      expect(result).to.deep.equal({
        minTemp: 15,
        maxTemp: 20,
        chanceRain: 0.83,
        rainFall: 2,
        cloudCover: 50,
      });
    });

    it("should throw an error when allResults is null", function () {
      expect(() => processResults(null)).to.throw();
    });

    it("should throw an error when allResults is missing required fields", function () {
      const allResults = {
        main: {
          temp_min: 288.15, // 15C
        },
      };
      expect(() => processResults(allResults)).to.throw();
    });
  });
});
