// Test generated by RoostGPT for test testingNjsUnit0812 using AI Type Vertex AI and AI Model code-bison-32k


// prepared-for-the-weather.test.js

const { averageTemp } = require('./prepared-for-the-weather');

describe('Average Temperature Calculator', () => {
  describe('Valid Inputs', () => {
    test('should return the average temperature', () => {
      expect(averageTemp(10, 20)).toBe(15);
      expect(averageTemp(0, 100)).toBe(50);
      expect(averageTemp(-10, 10)).toBe(0);
    });
  });

  describe('Edge Cases', () => {
    test('should return 0 for equal minimum and maximum temperatures', () => {
      expect(averageTemp(10, 10)).toBe(0);
    });
  });

  describe('Error Handling', () => {
    test('should throw an error for non-numeric inputs', () => {
      expect(() => averageTemp('a', 'b')).toThrow();
    });

    test('should throw an error for negative minimum temperatures', () => {
      expect(() => averageTemp(-10, 10)).toThrow();
    });
  });
});
