// Test generated by RoostGPT for test testingNjsUnit0812 using AI Type Vertex AI and AI Model code-bison-32k


// fetch-weather.test.js
const fetchWeather = require('./fetch-weather');
const request = require('request');

describe('fetchWeather', () => {
  // Mock the request function to control the response
  beforeEach(() => {
    request.mockImplementation((options, callback) => {
      callback(null, { statusCode: 200 }, {
        weather: [{ description: 'Clear' }]
      });
    });
  });

  test('should return weather data for a valid location', (done) => {
    fetchWeather('London', (weather) => {
      expect(weather).toHaveProperty('weather');
      expect(weather.weather[0].description).toBe('Clear');
      done();
    });
  });

  test('should handle errors and return an empty object', (done) => {
    // Simulate an error by setting the status code to 404
    request.mockImplementation((options, callback) => {
      callback(null, { statusCode: 404 }, {});
    });

    fetchWeather('Invalid Location', (weather) => {
      expect(weather).toEqual({});
      done();
    });
  });
});
