// Test generated by RoostGPT for test testingNjsUnit0812 using AI Type Vertex AI and AI Model code-bison-32k


// fetch-weather.test.js

import { getRainFall } from './fetch-weather';

describe('getRainFall', () => {
  test('should return 0 if rainObj is null or undefined', () => {
    expect(getRainFall(null)).toBe(0);
    expect(getRainFall(undefined)).toBe(0);
  });

  test('should return the rainfall amount for the last hour if available', () => {
    const rainObj = {
      '1h': 1.2,
      '2h': 0.8,
      '3h': 0.5,
    };
    expect(getRainFall(rainObj)).toBe(1.2);
  });

  test('should return the rainfall amount for the last 2 hours if available', () => {
    const rainObj = {
      '2h': 1.8,
      '3h': 0.7,
    };
    expect(getRainFall(rainObj)).toBe(1.8);
  });

  test('should return the rainfall amount for the last 3 hours if available', () => {
    const rainObj = {
      '3h': 2.5,
    };
    expect(getRainFall(rainObj)).toBe(2.5);
  });

  test('should return 0 if no rainfall data is available', () => {
    const rainObj = {};
    expect(getRainFall(rainObj)).toBe(0);
  });
});
