// Test generated by RoostGPT for test testingNjsUnit0812 using AI Type Vertex AI and AI Model code-bison-32k


// import the kelvinToCelcius function from fetch-weather.js
const { kelvinToCelcius } = require('./fetch-weather');

describe('Kelvin to Celsius Conversion', () => {
  // Test case 1: Valid Kelvin temperature conversion
  test('Converts Kelvin to Celsius correctly', () => {
    const kelvinTemp = 298;
    const expectedCelciusTemp = 25;
    expect(kelvinToCelcius(kelvinTemp)).toBe(expectedCelciusTemp);
  });

  // Test case 2: Edge case - Temperature at absolute zero
  test('Handles absolute zero conversion correctly', () => {
    const kelvinTemp = 0;
    const expectedCelciusTemp = -273;
    expect(kelvinToCelcius(kelvinTemp)).toBe(expectedCelciusTemp);
  });

  // Test case 3: Error handling - Non-numeric input
  test('Throws error for non-numeric input', () => {
    const invalidTemp = 'abc';
    expect(() => {
      kelvinToCelcius(invalidTemp);
    }).toThrowError('Invalid temperature value. Please provide a numeric value in Kelvin.');
  });
});
