// ********RoostGPT********
/*
Test generated by RoostGPT for test testM using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=869bcf28d1
ROOST_METHOD_SIG_HASH=75d10f69f9


*/

// ********RoostGPT********
const assert = require('assert');
const sinon = require('sinon');
const rawWeatherData = require('./rawWeatherData');
const preparingData = require('./preparing-data');

describe('Test that the data fetched from OpenWeatherMap is processed correctly', function () {
  let callback;

  beforeEach(function() {
    callback = sinon.stub();
    callback.withArgs("London").returns(rawWeatherData);
  });

  it('Should check fetched data is processed correctly', function () {
    const result = preparingData(callback("London"));
    assert.equal(result.city, "London");
    assert.equal(result.temperature, 280.32);
    assert.equal(result.humidity, 81);
    assert.equal(result.weather, "Clouds");
  });

  it('Should throw an error if no data is returned', function () {
    callback.withArgs("Unknown").returns(null);
    assert.throws(() => preparingData(callback("Unknown")), Error);
  });
});
