// ********RoostGPT********
/*
Test generated by RoostGPT for test testM using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=averageTemp_700473064c
ROOST_METHOD_SIG_HASH=averageTemp_db5e66b0a6


*/

// ********RoostGPT********
const expect = require('chai').expect;
const averageTemp = require('../weather/prepared-for-the-weather');

describe('averageTemp function test', function() {

  it('should return average when valid numbers are passed', function() {
    const result = averageTemp(2, 4);
    expect(result).to.equal(3);
  });

  it('should return NaN when non-numeric values are passed', function() {
    const result = averageTemp('a', 'b');
    expect(result).to.be.NaN;
  });

  it('should return NaN when one of the parameters is non-numeric', function() {
    const result = averageTemp(2, 'b');
    expect(result).to.be.NaN;
  });

  it('should return average when zero is passed', function() {
    const result = averageTemp(0, 4);
    expect(result).to.equal(2);
  });

});
