// ********RoostGPT********
/*
Test generated by RoostGPT for test testing-nodejs using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=averageTemp_c5e4f830d6
ROOST_METHOD_SIG_HASH=averageTemp_db5e66b0a6


*/

// ********RoostGPT********
// First, import the necessary modules
const { averageTemp } = require('../weather/prepared-for-the-weather');

// Define the test suite for the 'averageTemp' function
describe('averageTemp', () => {

  // Test case for valid numeric inputs
  test('should return the average of two numbers', () => {
    const result = averageTemp(10, 20);
    expect(result).toBe(15);
  });

  // Test case for non-numeric inputs
  test('should return NaN for non-numeric inputs', () => {
    const result = averageTemp('a', 'b');
    expect(result).toBeNaN();
  });

  // Test case for mixed inputs (numeric and non-numeric)
  test('should return NaN for mixed inputs', () => {
    const result = averageTemp(10, 'b');
    expect(result).toBeNaN();
  });

  // Test case for no inputs
  test('should return NaN for no inputs', () => {
    const result = averageTemp();
    expect(result).toBeNaN();
  });
});
