// ********RoostGPT********
/*
Test generated by RoostGPT for test checkNodejsDepsInstalled using AI Type Open AI and AI Model gpt-4


ROOST_TEST_HASH=4c53294148

*/

// ********RoostGPT********
const fetchWeather = require('./fetchWeather');
const prepareForWeather = require('./prepareForWeather');

describe('fetchWeather function', () => {
  
  let today;
  let weatherKit;
  
  beforeAll(() => {
    today = 'sunny';
    weatherKit = [
      { 'name': 'Umbrella', 'value': prepareForWeather.doINeed.umbrella(today) },
      { 'name': 'Suncream', 'value': prepareForWeather.doINeed.suncream(today) },
      { 'name': 'Jumper', 'value': prepareForWeather.doINeed.jumper(today) },
      { 'name': 'Water', 'value': prepareForWeather.doINeed.water(today) }
    ];
  });
  
  test('Should return correct weather kit for sunny day', () => {
    fetchWeather.fetchWeather('London', (weather) => {
      for (key in weatherKit) {
        expect(weather[key].value).toEqual(weatherKit[key].value);
        expect(weather[key].name).toEqual(weatherKit[key].name);
      }
    });
  });

  test('Should throw error on invalid location', () => {
    expect(() => fetchWeather.fetchWeather('InvalidLocation', () => {})).toThrow();
  });
});
