// ********RoostGPT********
/*
Test generated by RoostGPT for test testM using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=4c53294148
ROOST_METHOD_SIG_HASH=dc35180642


*/

// ********RoostGPT********
const expect = require('chai').expect;
const fetchWeather = require('./weather/app');
const prepareForWeather = require('./weather/prepareForWeather');

describe('fetchWeather', () => {
  let today;
  beforeEach(() => {
    today = {
      temperature: 25,
      rain: false,
      sun: true
    };
  });

  it('should prepare correct weather kit for sunny day', (done) => {
    fetchWeather.fetchWeather(today, (weatherKit) => {
      expect(weatherKit).to.be.an('array');
      expect(weatherKit).to.deep.include({ name: 'Umbrella', value: false });
      expect(weatherKit).to.deep.include({ name: 'Suncream', value: true });
      expect(weatherKit).to.deep.include({ name: 'Jumper', value: false });
      expect(weatherKit).to.deep.include({ name: 'Water', value: true });
      done();
    });
  });

  it('should prepare correct weather kit for rainy day', (done) => {
    today.rain = true;
    today.sun = false;
    
    fetchWeather.fetchWeather(today, (weatherKit) => {
      expect(weatherKit).to.be.an('array');
      expect(weatherKit).to.deep.include({ name: 'Umbrella', value: true });
      expect(weatherKit).to.deep.include({ name: 'Suncream', value: false });
      expect(weatherKit).to.deep.include({ name: 'Jumper', value: true });
      expect(weatherKit).to.deep.include({ name: 'Water', value: false });
      done();
    });
  });
});
