// ********RoostGPT********
/*
Test generated by RoostGPT for test testM using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=fetchWeather_e15d09d035
ROOST_METHOD_SIG_HASH=fetchWeather_2ec6f97b3f


*/

// ********RoostGPT********
const expect = require('chai').expect;
const nock = require('nock');
const fetchWeather = require('./fetch-weather');

describe('Fetch Weather', () => {
  beforeEach(() => {
    nock('http://api.openweathermap.org')
      .get('/data/2.5/weather?q=London&appid=aa0f1b0be45dca476178787f941c76dc')
      .reply(200, {
        weather: [{
          description: 'light rain'
        }],
        main: {
          temp: 289.5
        }
      });
  });

  it('Gets the correct weather for a location', (done) => {
    fetchWeather('London', (err, result) => {
      expect(result).to.deep.equal({
        weather: [{
          description: 'light rain'
        }],
        main: {
          temp: 289.5
        }
      });
      done();
    });
  });

  it('Handles errors', (done) => {
    nock('http://api.openweathermap.org')
      .get('/data/2.5/weather?q=Unknown&appid=aa0f1b0be45dca476178787f941c76dc')
      .replyWithError('Something went wrong');

    fetchWeather('Unknown', (err) => {
      expect(err).to.match(/Something went wrong/);
      done();
    });
  });
});
