// ********RoostGPT********
/*
Test generated by RoostGPT for test testJ using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=getRainFall_3237bb46a3
ROOST_METHOD_SIG_HASH=getRainFall_76e9e0bca8


*/

// ********RoostGPT********
const { getRainFall } = require('../weather/fetch-weather');

describe('getRainFall', () => {
  test('should return 0 when rainObj is null', () => {
    const result = getRainFall(null);
    expect(result).toBe(0);
  });

  test('should return 0 when rainObj does not contain "1h", "2h" or "3h" properties', () => {
    const result = getRainFall({});
    expect(result).toBe(0);
  });

  test('should return the value of "1h" property when it is present', () => {
    const result = getRainFall({ '1h': 1.5 });
    expect(result).toBe(1.5);
  });

  test('should return the value of "2h" property when "1h" is not present', () => {
    const result = getRainFall({ '2h': 2.5 });
    expect(result).toBe(2.5);
  });

  test('should return the value of "3h" property when "1h" and "2h" are not present', () => {
    const result = getRainFall({ '3h': 3.5 });
    expect(result).toBe(3.5);
  });
});
