// ********RoostGPT********
/*
Test generated by RoostGPT for test testM using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=getRainFall_3237bb46a3
ROOST_METHOD_SIG_HASH=getRainFall_76e9e0bca8


*/

// ********RoostGPT********
const expect = require('chai').expect;
const getRainFall = require('./fetch-weather');

describe('getRainFall', function() {
  let rainObj;

  beforeEach(function() {
    rainObj = {};
  });

  it('should return 0 if no object is provided', function() {
    expect(getRainFall()).to.equal(0);
  });

  it('should return 0 if object does not contain "1h", "2h", or "3h" properties', function() {
    expect(getRainFall(rainObj)).to.equal(0);
  });

  it('should return the value of "1h" property if it exists', function() {
    rainObj['1h'] = 5;
    expect(getRainFall(rainObj)).to.equal(5);
  });

  it('should return the value of "2h" property if it exists and "1h" does not exist', function() {
    rainObj['2h'] = 6;
    expect(getRainFall(rainObj)).to.equal(6);
  });

  it('should return the value of "3h" property if it exists and neither "1h" nor "2h" exist', function() {
    rainObj['3h'] = 7;
    expect(getRainFall(rainObj)).to.equal(7);
  });
});
