// ********RoostGPT********
/*
Test generated by RoostGPT for test testJ using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=kelvinToCelcius_c4e254281d
ROOST_METHOD_SIG_HASH=kelvinToCelcius_5ac945d542


*/

// ********RoostGPT********
const { kelvinToCelcius } = require('../weather/fetch-weather');

describe('kelvinToCelcius function tests', () => {
  
  test('should correctly convert kelvin to celcius', () => {
    const kTemp = 300;
    const result = kelvinToCelcius(kTemp);
    expect(result).toBe(27);
  });

  test('should return 0 when input is 273', () => {
    const kTemp = 273;
    const result = kelvinToCelcius(kTemp);
    expect(result).toBe(0);
  });

  test('should throw an error when input is not a number', () => {
    const kTemp = 'abc';
    expect(() => kelvinToCelcius(kTemp)).toThrow();
  });
  
  test('should throw an error when input is less than 0', () => {
    const kTemp = -5;
    expect(() => kelvinToCelcius(kTemp)).toThrow();
  });

});
