// ********RoostGPT********
/*
Test generated by RoostGPT for test testJ using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=kelvinToCelcius_c4e254281d
ROOST_METHOD_SIG_HASH=kelvinToCelcius_5ac945d542


*/

// ********RoostGPT********
const { kelvinToCelcius } = require('../weather/fetch-weather');

describe('kelvinToCelcius function tests', () => {
  
  test('Convert a valid kelvin temperature to celcius', () => {
    const kelvinTemp = 300;
    const expectedCelcius = 27;
    expect(kelvinToCelcius(kelvinTemp)).toBe(expectedCelcius);
  });

  test('Convert zero kelvin to celcius', () => {
    const kelvinTemp = 0;
    const expectedCelcius = -273;
    expect(kelvinToCelcius(kelvinTemp)).toBe(expectedCelcius);
  });

  test('Return NaN for non-numeric input', () => {
    const kelvinTemp = 'a string';
    expect(kelvinToCelcius(kelvinTemp)).toBeNaN();
  });

  test('Return NaN for undefined input', () => {
    const kelvinTemp = undefined;
    expect(kelvinToCelcius(kelvinTemp)).toBeNaN();
  });

});
