// ********RoostGPT********
/*
Test generated by RoostGPT for test testJ using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=printLine_adf0a41ef1
ROOST_METHOD_SIG_HASH=printLine_a459837dee


*/

// ********RoostGPT********
const { printLine } = require('./app');

describe('printLine function', () => {
  let consoleSpy;

  beforeEach(() => {
    consoleSpy = jest.spyOn(console, 'log').mockImplementation();
  });

  afterEach(() => {
    consoleSpy.mockRestore();
  });

  test('should print green checkmark with text when required is true', () => {
    printLine(true, 'Hello World');
    expect(consoleSpy).toHaveBeenCalledWith('\u2714 Hello World');
  });

  test('should print red cross with text when required is false', () => {
    printLine(false, 'Hello World');
    expect(consoleSpy).toHaveBeenCalledWith('\u2716 Hello World');
  });
});
