// ********RoostGPT********
/*
Test generated by RoostGPT for test checkNodejsDepsInstalled using AI Type Open AI and AI Model gpt-4


ROOST_TEST_HASH=printLine_adf0a41ef1

*/

// ********RoostGPT********
const { printLine } = require('./app');

describe('printLine function', () => {
  let consoleOutput = [];
  const originalLog = console.log;

  beforeEach(() => {
    console.log = message => consoleOutput.push(message);
  });

  afterEach(() => {
    consoleOutput = [];
    console.log = originalLog;
  });

  test('should print green text with checkmark when required is true', () => {
    printLine(true, 'Test message');
    expect(consoleOutput[0]).toBe('\u2714 Test message');
  });

  test('should print red text with cross mark when required is false', () => {
    printLine(false, 'Test message');
    expect(consoleOutput[0]).toBe('\u2716 Test message');
  });
});
