// ********RoostGPT********
/*
Test generated by RoostGPT for test testM using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=printLine_adf0a41ef1
ROOST_METHOD_SIG_HASH=printLine_a459837dee


*/

// ********RoostGPT********
const expect = require('chai').expect;
const sinon = require('sinon');
const colors = require('colors');
const app = require('./app');

describe('app.js Tests', function() {
  let consoleLog;

  beforeEach(function() {
    consoleLog = sinon.stub(console, 'log');
  });

  afterEach(function() {
    consoleLog.restore();
  });

  it('should print green text with checkmark when required is true', function() {
    const text = 'Test message';
    app.printLine(true, text);
    expect(consoleLog.calledOnce).to.be.true;
    expect(consoleLog.calledWith((String.fromCharCode(10004) + " " + text).green)).to.be.true;
  });

  it('should print red text with cross mark when required is false', function() {
    const text = 'Test message';
    app.printLine(false, text);
    expect(consoleLog.calledOnce).to.be.true;
    expect(consoleLog.calledWith((String.fromCharCode(10006) + " " + text).red)).to.be.true;
  });
});
